---

- name: Install system packages
  apt:
    name: "{{ item }}"
    state: latest
  tags: [apt, openwisp2, iptables]
  with_items:
    - iptables-persistent

- name: Copy firewall init script into place.
  template:
    src: firewall.sh
    dest: "{{ openwisp2_iptables_script }}"
    owner: root
    group: root
    mode: 0755
  notify: [start-firewall, iptables-save]
  tags: [openwisp2, iptables]

- name: Ensure firewall is active
  shell: iptables -L -v | wc -l
  register: iptables_check
  changed_when: iptables_check.stdout|int < 10
  notify: [start-firewall]
  tags: [openwisp2, iptables]
